name: Lint Dockerfile

on:
  push:
    paths:
     - 'Dockerfile'
  workflow_dispatch:
    inputs:
      input:
        description: "Manual Execution"
        required: true
        default: "Manual Execution"

jobs:
  Lint:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@master
      with:
        dockerfile: "Dockerfile"
        failure-threshold: error
        format: json
